### ISSUE TITLE
noob question about macros.

### ISSUE THREAD

**Issue by ran-codes** [emilyriederer/dbt_dplyr#19]
Hi emily. thank you so much for putting this together. its a great package. I am a dplyr person at heart and a complete dbt nooob and I want to ask a pretty general question just to get the lay of the land so I don't write any macros that exist.

**Are there other of these dbt macros libraries/collections out there that you recommend checking out?**

**Comment by emilyriederer** [comment]
Hi @ran-codes ! Thanks for the note. I'm so glad if the package is useful. 

You can find the full set of available packages here: https://hub.getdbt.com/

Some that I will callout as specifically useful:

- `dbt-utils`: Feels very dplyr/tidyr-esque not so much in what it does but rather in the level of higher-level "just what you need" functions (e.g. out-of-the-box tests, nice spine generation, etc.)
- `dbt-expectations`: Really rich set of data quality checks
- `dbt-datamocktool`: Super clever idea for testing but only available on certain databases
- `activity-schema`: Depending on your problem-space or data type, this is a neat way to think about structuring data. Since tidyverse places so much emphasis on data structure, it might be the kind of thing that excites you too! (Although it promotes very, very, very *long* data versus "tidy" persay)

A lot of the others seem to be more about working with specific connectors or data sources so YMMV

Hope that helps!
