### ISSUE TITLE
License for this project?

### ISSUE THREAD

**Issue by joyzheng** [emilyriederer/dbt_dplyr#20]
Hi -- thanks for putting this package together! Is there a license that this project is released under? I would love to use this for work but am not sure what the license terms are.

**Comment by emilyriederer** [comment]
Thanks so much for your interest and for flagging the license issue, @joyzheng ! I certainly intended to have a permissive license here. Since I wrote the package, I see this has now also been added to the dbt packages [best practices](https://github.com/dbt-labs/hubcap/pull/302/files#diff-dcb00980d2c81eb60e6ef190775fd8a5c9ca6b739206fc92943abba77a8ff3fb) guide. 

I just added an Apache 2.0 license, the same one dbt uses. Hope that helps!
